spring.application.name=SimpleBank

spring.datasource.url=jdbc:h2:mem:simplebank;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2NzgxMjM0NTY3OA==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

admin.bootstrap.email=admin@simplebank.local
admin.bootstrap.password=Admin123